### ISSUE TITLE
background color settings for export png

### ISSUE THREAD

**Issue by zhiangcai** [sgratzl/cytoscape.js-layers#30] opened 2023-10-13 03:26 UTC
I create the custom canvas layer and set bg="#fff" when exporting the canvas, but the exported background color is not white.

**Comment by sgratzl** [comment] 2023-10-21 01:00
cannot reproduce with the latest version v2.4.2

**Comment by sgratzl** [comment] 2024-01-21 18:02
closing, please reopen if occurs

**Closed by sgratzl** 2024-01-21 18:02 UTC
Labels: bug, help wanted
